# ~/.config/ddns-client/config.yaml
waitTime: 1                # time to wait between HTTP request retry
maxAttempts: 5             # max # to retry HTTP request
checkIPChange: false       # Check if DNS points to correct IP address before updating DDNS
logPath: "ddns-client.log" # path to log file
domain: ""                 # domain name to solve
ddnsUser: ""               # User name of DDNS Now
token: ""                  # Token of DDNS Now
